function onload()
    self.createButton({
        label="->", click_function="next", function_owner=self,
        position={0.5,0.08,-1.84}, rotation={0,0,0}, height=80, width=120, font_size=50
    })
    self.createButton({
        label="<-", click_function="back", function_owner=self,
        position={-0.5,0.08,-1.84}, rotation={0,0,0}, height=80, width=120, font_size=50
    })
end

function next()
    self.setState(10)
end

function back()
    self.setState(8)
end